#!/usr/bin/env python3
"""Export a trained OpenDeFeedback tiny model to embedded C weights (STUB).

Placeholder documenting the export interface. The real version will load a
trained checkpoint, quantise it, and emit a header that replaces
src/ml/ModelWeightsStub.h so the weights are baked into the plugin binary — no
external runtime, no file I/O at audio time.
"""

from __future__ import annotations

import argparse
import datetime


HEADER_TEMPLATE = """\
// AUTO-GENERATED by training/export_model_stub.py on {date}
// Do not edit by hand. Replaces the hand-written ModelWeightsStub.h.
#pragma once
#include <cstdint>
namespace odf {{ namespace model {{
static constexpr int   kWeightsVersion = {version};
static constexpr int   kInputSize      = {input_size};
static constexpr int   kHiddenSize     = {hidden_size};
static constexpr int   kNumOutputs     = {num_outputs};
static constexpr int   kNumWeights     = {num_weights};
static constexpr float kWeights[{num_weights_or_1}] = {{ {weights} }};
}} }} // namespace odf::model
"""


def export(args):
    print("[export_model_stub] STUB — emitting a neutral (empty) weights header.")
    # A real export would load args.checkpoint, quantise, and fill these in.
    text = HEADER_TEMPLATE.format(
        date=datetime.date.today().isoformat(),
        version=0,            # 0 == stub / inert
        input_size=12,
        hidden_size=0,
        num_outputs=4,
        num_weights=0,
        num_weights_or_1=1,
        weights="0.0f",
    )
    if args.dry_run:
        print(text)
    else:
        with open(args.out, "w", encoding="utf-8") as f:
            f.write(text)
        print(f"  wrote {args.out} (still a neutral stub).")


def main():
    ap = argparse.ArgumentParser(description="Export OpenDeFeedback weights (STUB).")
    ap.add_argument("--checkpoint", type=str, default="checkpoints/model.pt")
    ap.add_argument("--out", type=str, default="../src/ml/ModelWeightsStub.h")
    ap.add_argument("--dry-run", action="store_true", help="print instead of writing")
    export(ap.parse_args())


if __name__ == "__main__":
    main()
